### ISSUE TITLE
terminado

### ISSUE THREAD

**Issue by Marinaperezmaza** [DeustoPWEB2018/Elementos-de-la-UX#15]
terminado

**Comment by angielozanogr** [comment]
@mberasategi intento hacer pull y no me permite. No tengo claro si se cambio el nombre por "como-conocer-necesidades-usuarios" @Marinaperezmaza  

C:\Users\Anlozana\Documents\Elementos-de-la-UX>git pull origin usuarios
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by mirenbz** [comment]
@angielozanogr , parece que tienes archivos en tu ordenador que has modificado, y git no sabe cómo combinarlos cuando haces pull. 

Haz `git status` y deja aquí una captura de pantalla o copia y pega el resultado.

**Comment by angielozanogr** [comment]
@mberasategi 
C:\Users\Anlozana>cd Documents

C:\Users\Anlozana\Documents>cd Elementos-de-la-UX

C:\Users\Anlozana\Documents\Elementos-de-la-UX>git status
On branch usuarios
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

        deleted by them: 1-estrategia/Usuarios.md
        both modified:   como-conocer-necesidades-usuarios.md

no changes added to commit (use "git add" and/or "git commit -a")

C:\Users\Anlozana\Documents\Elementos-de-la-UX>

**Comment by mirenbz** [comment]
Angie, en cualquier caso no hace falta que hagas pull del branch `usuarios` ahora. Una vez que ya están integrados [los cambios que habéis ido haciendo](https://github.com/DeustoPWEB2018/Elementos-de-la-UX/pull/11) ahí en el branch `master`, simplemente tienes que eliminar el branch `usuarios` de tu ordenador como os he indicado en [este comentario](https://github.com/DeustoPWEB2018/Elementos-de-la-UX/pull/11#issuecomment-428120550) (sigue los pasos 2 y 3).

**Comment by mirenbz** [comment]
¿Todo bien @angielozanogr ? Voy a cerrar este issue, deja un comentario en [vuestro pull request](https://github.com/DeustoPWEB2018/Elementos-de-la-UX/pull/11) si tienes algún problema.
